# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CatastoIT_GML_Merger_ProDialog
                                 A QGIS plugin CatastoIT_GML_Merger_Pro

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Salvatore Fiandaca
        email                : Salvatore Fiandaca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import sys

sys.path.append(os.path.dirname(__file__))
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QProgressBar, QPushButton, QListWidgetItem
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import Qt
from .regions import REGIONS, get_provinces
from .comuni import get_comuni_by_province

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'CatastoIT_GML_Merger_Pro_dialog_base.ui'), resource_suffix='')


class CatastoIT_GML_Merger_ProDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(CatastoIT_GML_Merger_ProDialog, self).__init__(parent)
        self.setupUi(self)

        # Aggiungi il pulsante di minimizzazione
        self.setWindowFlags(self.windowFlags() | Qt.WindowMinimizeButtonHint)

        # Aggiungi il widget di selezione CRS
        # self.mQgsProjectionSelectionWidget = QgsProjectionSelectionWidget(self)
        # self.mQgsProjectionSelectionWidget.setCrs(QgsCoordinateReferenceSystem('EPSG:6706'))
        # Aggiungi il widget al layout appropriato - modifica in base alla tua UI
        # self.layout().addWidget(self.mQgsProjectionSelectionWidget)

        if not hasattr(self, 'btn_cancel'):
            self.btn_cancel = QPushButton("Annulla", self)
            self.btn_cancel.setVisible(False)
            self.btn_cancel.clicked.connect(self.cancel_operation)
            self.layout().addWidget(self.btn_cancel)

        # Imposta il placeholder per il widget di selezione cartella
        self.le_folder.lineEdit().setPlaceholderText("ES: C:\\Users\\<nome utente>\\Downloads\\munnizza")

        # Imposta il placeholder per il widget di selezione cartella temporanea
        self.le_temp_folder.lineEdit().setPlaceholderText("ES: /media/emanuele/extra/temp (opzionale - usa cartella di sistema se vuoto)")

        # Imposta i placeholder direttamente sui QLineEdit (non più QgsFileWidget)
        self.le_map_output.setPlaceholderText("Solo nome file (es. mappe_catastali)")
        self.le_ple_output.setPlaceholderText("Solo nome file (es. particelle_catastali)")
        self.le_url.setPlaceholderText("ES: https://wfs.cartografia.agenziaentrate.gov.it/inspire/wfs/GetDataset.php?dataset=SICILIA.zip")

        # Configura il pulsante per mostrare/nascondere la guida
        self.btn_toggle_help.clicked.connect(self.toggle_help_panel)

        # Popola il combobox delle regioni
        self.populate_regions()

        def updateFileType():
            ext = self.cb_format.currentText().lower()
            self.le_map_output.setPlaceholderText(f"Solo nome file (es. mappe_catastali.{ext})")
            self.le_ple_output.setPlaceholderText(f"Solo nome file (es. particelle_catastali.{ext})")

            if self.le_map_output.text():
                base_path = self.le_map_output.text().split('.')[0]
                self.le_map_output.setText(f"{base_path}.{ext}")

            if self.le_ple_output.text():
                base_path = self.le_ple_output.text().split('.')[0]
                self.le_ple_output.setText(f"{base_path}.{ext}")

        self.cb_format.currentTextChanged.connect(updateFileType)

        # Connetti il cambio di regione all'aggiornamento delle province
        self.cb_region.currentTextChanged.connect(self.update_provinces)

        # Connetti il cambio di selezione province all'aggiornamento dei comuni
        self.list_provinces.itemSelectionChanged.connect(self.update_comuni_list)

        self.setup_help_content()
        self.update_provinces()

    def cancel_operation(self):
        """Cancella l'operazione in corso"""
        pass

    def closeEvent(self, event):
        self.le_folder.setFilePath("")
        self.le_temp_folder.setFilePath("")
        self.le_map_output.setText("")
        self.le_ple_output.setText("")
        self.list_comuni.clear()
        self.cb_file_type.setCurrentIndex(0)
        self.cb_format.setCurrentIndex(0)
        self.cb_region.setCurrentIndex(0)
        self.le_url.clear()
        self.text_log.clear()

        print("close!")

    def populate_regions(self):
        """Popola il combobox delle regioni."""
        self.cb_region.clear()
        self.cb_region.addItems(REGIONS)

    def get_selected_region(self):
        """Restituisce la regione selezionata."""
        return self.cb_region.currentText()

    def update_provinces(self):
        """Aggiorna il combobox delle province in base alla regione selezionata."""
        region = self.cb_region.currentText()
        provinces = get_provinces(region)

        self.list_provinces.clear()
        self.list_provinces.addItems(provinces)
        self.list_comuni.clear()

    def update_comuni_list(self):
        """Popola list_comuni con i comuni della provincia selezionata.

        Funziona solo quando è selezionata esattamente una provincia.
        Con più province selezionate svuota la lista (troppi comuni da mostrare).
        """
        self.list_comuni.clear()
        selected = self.list_provinces.selectedItems()
        if len(selected) != 1:
            return
        sigla = selected[0].text().strip().upper()
        comuni = get_comuni_by_province(sigla)  # [(codice, nome), ...]
        for codice, nome in comuni:
            item = QListWidgetItem(nome)
            item.setData(Qt.UserRole, codice)
            self.list_comuni.addItem(item)

    def toggle_help_panel(self):
        """Gestisce la visualizzazione/nascondimento del pannello della guida."""
        if self.help_browser.isVisible():
            self.help_browser.hide()
            self.btn_toggle_help.setIcon(QIcon(":/qt-project.org/styles/commonstyle/images/right-32.png"))
            self.btn_toggle_help.setToolTip("Mostra guida")
        else:
            self.help_browser.show()
            self.btn_toggle_help.setIcon(QIcon(":/qt-project.org/styles/commonstyle/images/left-32.png"))
            self.btn_toggle_help.setToolTip("Nascondi guida")

    def setup_help_content(self):
        """Carica il contenuto della guida dal file HTML esterno"""
        help_file_path = os.path.join(os.path.dirname(__file__), 'help_content.html')
        if os.path.exists(help_file_path):
            with open(help_file_path, 'r', encoding='utf-8') as html_file:
                help_content = html_file.read()
                self.help_browser.setHtml(help_content)
        else:
            self.help_browser.setHtml("<p>File della guida non trovato.</p>")
