# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CatastoIT_GML_Merger_Pro
                                 A QGIS plugin CatastoIT_GML_Merger_Pro
                                 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Salvatore Fiandaca
        email                : pigrecoinfinito@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# -- Import moduli standard Python --
import gc
import io
import os
import os.path
import shutil
import sqlite3
import tempfile
import time
import urllib.request
from datetime import datetime, timedelta
from zipfile import ZipFile

# -- Import moduli di terze parti --
from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator, QVariant, Qt, pyqtSignal
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QApplication, QListWidget
from qgis.core import Qgis, QgsCoordinateReferenceSystem, QgsField, QgsMessageLog, QgsProject, QgsVectorLayer, QgsTask, QgsApplication
import processing

# -- Import moduli locali del progetto --
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .CatastoIT_GML_Merger_Pro_dialog import CatastoIT_GML_Merger_ProDialog
from .comuni import COMUNI_BY_CODE

directory_temporanea = ""                


class CatastoIT_GML_Merger_Pro:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CatastoIT_GML_Merger_Pro_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&CatastoIT_GML_Merger_Pro')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CatastoIT_GML_Merger_Pro', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/CatastoIT_GML_Merger_Pro/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'CatastoIT_GML_Merger_Pro'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&CatastoIT_GML_Merger_Pro'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        if self.first_start == True:
            self.first_start = False
            self.dlg = CatastoIT_GML_Merger_ProDialog()
            
            # Inizializziamo l'attributo per tenere traccia del task attivo
            self.current_task = None
            self.processing_active = False
            
            # Inizializza il widget di proiezione con il CRS predefinito
            from qgis.core import QgsCoordinateReferenceSystem
            self.dlg.mQgsProjectionSelectionWidget.setCrs(QgsCoordinateReferenceSystem('EPSG:6706'))
            
        self.dlg.show()
            
        def log_message(msg):
            print(msg)
            QgsMessageLog.logMessage(msg, 'Elaborazione GML')
            self.dlg.text_log.append(msg)
            self.dlg.text_log.repaint()
            
        def collect_inputs():
            inputs = {}
            
            file_type = self.dlg.cb_file_type.currentText()
            inputs['file_type'] = file_type
            print(inputs['file_type'])
            
            inputs['main_folder'] = self.dlg.le_folder.filePath()
            print(inputs['main_folder'])
            
            # Cartella temporanea opzionale
            inputs['temp_folder'] = self.dlg.le_temp_folder.filePath()
            if inputs['temp_folder']:
                print(f"Cartella temporanea personalizzata: {inputs['temp_folder']}")
                log_message(f"Usando cartella temporanea personalizzata: {inputs['temp_folder']}")
                # Verifica che la cartella esista e sia scrivibile
                if not os.path.exists(inputs['temp_folder']):
                    log_message("<span style='color:red;font-weight:bold;'>ERRORE: La cartella temporanea specificata non esiste</span>")
                    return None
                if not os.access(inputs['temp_folder'], os.W_OK):
                    log_message("<span style='color:red;font-weight:bold;'>ERRORE: La cartella temporanea specificata non è scrivibile</span>")
                    return None
            else:
                print("Usando cartella temporanea di sistema")
            
            # Verifica che sia stata selezionata una cartella di lavoro
            if not inputs['main_folder']:
                log_message("<span style='color:red;font-weight:bold;'>ERRORE: Nessuna cartella di lavoro selezionata</span>")
                return None
            
            # Ottieni il CRS selezionato dal widget di proiezione
            crs = self.dlg.mQgsProjectionSelectionWidget.crs()
            inputs['target_crs'] = crs.authid() if crs.isValid() else 'EPSG:6706'  # Default a EPSG:6706 se non valido
            print(f"CRS selezionato: {inputs['target_crs']}")
            
            # Verifica lo stato del checkbox per sezione censuaria
            inputs['add_sezione_censuaria'] = self.dlg.cb_sez_censu.isChecked()
            if inputs['add_sezione_censuaria']:
                log_message("Opzione 'Aggiungi Sezione Censuaria nelle Particelle' attivata")
                print("Sezione censuaria attivata")

            # Verifica lo stato del checkbox per nome comune
            inputs['add_nome_comune'] = self.dlg.cb_nome_comune.isChecked()
            if inputs['add_nome_comune']:
                log_message("Opzione 'Aggiungi Nome Comune' attivata")
            
            inputs['url'] = self.dlg.le_url.text()
            if not inputs['url']:
                log_message("<span style='color:red;font-weight:bold;'>ERRORE: URL non specificato</span>")
                return None
            print(inputs['url'])
            
            # Ottieni le province selezionate dalla list_provinces
            selected_items = self.dlg.list_provinces.selectedItems()
            if not selected_items:
                log_message("<span style='color:red;font-weight:bold;'>ERRORE: Nessuna provincia selezionata</span>")
                return None
            
            # Crea una lista di codici provincia dalle selezioni
            province_codes = [item.text().strip().upper() for item in selected_items]
            inputs['province_code'] = ','.join(province_codes)
            inputs['filter_by_province'] = True
            
            log_message(f"Province selezionate: {inputs['province_code']}")
            print(f"Province selezionate: {inputs['province_code']}")

            # Filtro comuni: legge tutti gli item di list_comuni_selezionati
            n = self.dlg.list_comuni_selezionati.count()
            if n > 0:
                comuni_list = [self.dlg.list_comuni_selezionati.item(i).data(Qt.UserRole) for i in range(n)]
                comuni_nomi = [self.dlg.list_comuni_selezionati.item(i).text() for i in range(n)]
                inputs['comuni_filter'] = comuni_list
                log_message(f"Filtro comuni attivo ({n}): {', '.join(comuni_nomi)}")
            else:
                inputs['comuni_filter'] = []

            formats = {
                'GPKG': '.gpkg'
            }

            format_name = self.dlg.cb_format.currentText()
            inputs['format_name'] = format_name
            inputs['output_extension'] = formats[format_name]
            print(inputs['output_extension'])
            
            if file_type in ['Mappe (MAP)', 'Entrambi']:
                # Ottieni solo il nome del file, non il percorso
                map_filename = self.dlg.le_map_output.text()
                if not map_filename:
                    log_message("<span style='color:red;font-weight:bold;'>ERRORE: Nome file di output MAP non specificato</span>")
                    return None

                # Valida i caratteri del nome file
                invalid_chars = set('<>:"/\\|?*')
                if any(c in map_filename for c in invalid_chars):
                    log_message("<span style='color:red;font-weight:bold;'>ERRORE: Nome file MAP contiene caratteri non validi</span>")
                    return None
                if len(map_filename) > 200:
                    log_message("<span style='color:red;font-weight:bold;'>ERRORE: Nome file MAP troppo lungo (max 200 caratteri)</span>")
                    return None

                # Aggiungi estensione se mancante
                if not map_filename.endswith(formats[format_name]):
                    map_filename += formats[format_name]
                
                # Componi il percorso completo usando la cartella principale
                map_output = os.path.join(inputs['main_folder'], map_filename)
                inputs['map_output'] = map_output
                print(inputs['map_output'])
            
            if file_type in ['Particelle (PLE)', 'Entrambi']:
                # Ottieni solo il nome del file, non il percorso
                ple_filename = self.dlg.le_ple_output.text()
                if not ple_filename:
                    log_message("<span style='color:red;font-weight:bold;'>ERRORE: Nome file di output PLE non specificato</span>")
                    return None

                # Valida i caratteri del nome file
                invalid_chars = set('<>:"/\\|?*')
                if any(c in ple_filename for c in invalid_chars):
                    log_message("<span style='color:red;font-weight:bold;'>ERRORE: Nome file PLE contiene caratteri non validi</span>")
                    return None
                if len(ple_filename) > 200:
                    log_message("<span style='color:red;font-weight:bold;'>ERRORE: Nome file PLE troppo lungo (max 200 caratteri)</span>")
                    return None

                # Aggiungi estensione se mancante
                if not ple_filename.endswith(formats[format_name]):
                    ple_filename += formats[format_name]
                
                # Componi il percorso completo usando la cartella principale
                ple_output = os.path.join(inputs['main_folder'], ple_filename)
                inputs['ple_output'] = ple_output
                print(inputs['ple_output'])

            inputs['load_layers'] = self.dlg.cb_load_layers.isChecked()
            print(inputs['load_layers'])

            granularity_map = {
                0: 'unico',
                1: 'per_provincia',
                2: 'per_comune',
            }
            inputs['output_granularity'] = granularity_map.get(self.dlg.cb_output_granularity.currentIndex(), 'unico')
            
            self.dlg.text_log.clear()
            log_message("<span style='color:green;font-weight:bold;'>Parametri verificati correttamente</span>")
            
            return inputs

        def process_gml_files():
            global directory_temporanea
            
            try:
                # Inizializza lo stato di elaborazione
                self.processing_active = True
                
                # Abilita il pulsante di stop e disabilita quello di processo
                self.dlg.btn_stop.setEnabled(True)
                self.dlg.btn_process.setEnabled(False)
                
                inputs = collect_inputs()
                if not inputs:
                    log_message("Operazione annullata: verifica i parametri inseriti")
                    self.reset_processing_state()
                    return
                
                self.dlg.setWindowTitle("Catasto IT GML Merger PRO - Elaborazione in corso")
                
                # Crea e configura il task
                task = GmlProcessingTask('Elaborazione GML', inputs)
                
                # Connetti i segnali agli slot
                task.log_message.connect(log_message)
                task.task_completed.connect(self.on_task_completed)
                
                # Aggiungi il task al gestore task di QGIS
                QgsApplication.taskManager().addTask(task)
                self.current_task = task
                
                log_message("Task avviato in background...(Puoi continuare a lavorare in QGIS, riduci a icona il Plugin!)")
                
            except Exception as e:
                log_message(f"\nSi è verificato un errore durante l'avvio del task: {str(e)}")
                import traceback
                log_message(f"\nDettagli errore:\n{traceback.format_exc()}")
                self.reset_processing_state()

        def pulisci_temporanea():
            """Pulisce le directory temporanee in modo sicuro per evitare crash"""
            global directory_temporanea
            dir_path = directory_temporanea
            
            try:
                if dir_path and os.path.exists(dir_path):
                    log_message("Inizio pulizia directory temporanea...")
                    
                    # Libera tutti i layer in modo sicuro
                    try:
                        project = QgsProject.instance()
                        layers_to_remove = []
                        
                        # Prima raccogli tutti i layer da rimuovere
                        for layer_id, layer in list(project.mapLayers().items()):
                            try:
                                if layer and hasattr(layer, 'source') and layer.source():
                                    if dir_path in layer.source():
                                        layers_to_remove.append(layer_id)
                            except Exception:
                                # Ignora errori su singoli layer
                                continue
                        
                        # Poi rimuovi i layer uno per uno
                        for layer_id in layers_to_remove:
                            try:
                                project.removeMapLayer(layer_id)
                            except Exception:
                                continue
                                
                        if layers_to_remove:
                            log_message(f"Rimossi {len(layers_to_remove)} layer temporanei")
                            
                    except Exception as e:
                        log_message(f"Avviso durante rimozione layer: {str(e)}")
                    
                    # Forza garbage collection in modo più sicuro
                    try:
                        gc.collect()
                        time.sleep(0.5)  # Ridotto il tempo di attesa
                    except Exception:
                        pass
                    
                    # Prova a rimuovere la directory
                    try:
                        shutil.rmtree(dir_path)
                        log_message(f"Directory {dir_path} rimossa correttamente")
                        directory_temporanea = ""  # Reset della variabile globale
                    except Exception as e:
                        # Fallback: pulizia manuale più sicura
                        log_message(f"Pulizia manuale della directory temporanea...")
                        try:
                            for root, dirs, files in os.walk(dir_path, topdown=False):
                                # Rimuovi i file
                                for file in files:
                                    try:
                                        file_path = os.path.join(root, file)
                                        if os.path.exists(file_path):
                                            os.remove(file_path)
                                    except Exception:
                                        continue
                                # Rimuovi le directory vuote
                                for dir_name in dirs:
                                    try:
                                        dir_to_remove = os.path.join(root, dir_name)
                                        if os.path.exists(dir_to_remove):
                                            os.rmdir(dir_to_remove)
                                    except Exception:
                                        continue
                            # Rimuovi la directory principale
                            if os.path.exists(dir_path):
                                os.rmdir(dir_path)
                            log_message(f"Directory {dir_path} pulita manualmente")
                            directory_temporanea = ""
                        except Exception as e2:
                            log_message(f"Avviso: Pulizia parziale della directory temporanea")
                            log_message("Alcuni file temporanei saranno puliti al riavvio del sistema")
                else:
                    log_message("Nessuna directory temporanea da pulire")
                    
            except Exception as main_error:
                log_message(f"Errore durante pulizia: {str(main_error)}")
                log_message("Il plugin continuerà a funzionare normalmente")

            # Resetta l'interfaccia
            self.dlg.le_folder.setFilePath("")
            self.dlg.le_map_output.setText("")  # Usa setText invece di setFilePath
            self.dlg.le_ple_output.setText("")  # Usa setText invece di setFilePath
            self.dlg.cb_file_type.setCurrentIndex(0)
            self.dlg.cb_format.setCurrentIndex(0)
            self.dlg.cb_region.setCurrentIndex(0)
            self.dlg.list_provinces.clearSelection()  # Cancella le selezioni dalla lista
            self.dlg._reset_comuni_widget()
            self.dlg.cb_region.setEnabled(True)
            self.dlg.le_url.setEnabled(True)
            self.dlg.le_url.clear()
            self.dlg.text_log.clear()
            self.dlg.setWindowTitle("Catasto IT GML Merger PRO")
            
            # Chiudi il dialog alla fine
            self.dlg.hide()

        def url_update():
            self.dlg.le_url.setText("https://wfs.cartografia.agenziaentrate.gov.it/inspire/wfs/GetDataset.php?dataset=" + self.dlg.cb_region.currentText() + ".zip")
            
        def aggiorna_campi_output():
            """Attiva o disattiva i campi di output in base al tipo di file selezionato"""
            file_type = self.dlg.cb_file_type.currentText()
            
            # Gestisci i widget per l'output MAP
            map_enabled = file_type in ["Mappe (MAP)", "Entrambi"]
            self.dlg.le_map_output.setEnabled(map_enabled)
            
            # Gestisci i widget per l'output PLE
            ple_enabled = file_type in ["Particelle (PLE)", "Entrambi"]
            self.dlg.le_ple_output.setEnabled(ple_enabled)
            self.dlg.cb_sez_censu.setVisible(ple_enabled)  # Mostra l'opzione sezione censuaria solo quando PLE è abilitato
            
            # Aggiorna placeholder text per indicare che è richiesto solo il nome del file
            self.dlg.le_map_output.setPlaceholderText("Solo nome file (es. mappe_catastali)")
            self.dlg.le_ple_output.setPlaceholderText("Solo nome file (es. particelle_catastali)")
        
        self.dlg.cb_region.currentIndexChanged.connect(url_update)
        self.dlg.cb_file_type.currentIndexChanged.connect(aggiorna_campi_output)                                                       
        self.dlg.btn_process.clicked.connect(process_gml_files)
        self.dlg.btn_close.clicked.connect(pulisci_temporanea)
        self.dlg.btn_stop.clicked.connect(self.stop_processing)  # Ora funzionerà correttamente
        self.dlg.btn_stop.setEnabled(False)  # Disabilitato all'avvio
        
        # Imposta lo stato iniziale dei campi di output
        aggiorna_campi_output()

    def stop_processing(self):
        """Interrompe il processo di elaborazione in corso"""
        if self.processing_active and self.current_task:
            self.processing_active = False
            self.current_task.cancel()
            self.dlg.text_log.append("\n<span style='color:red;font-weight:bold;'>Interruzione richiesta dall'utente...</span>")
            self.dlg.text_log.append("L'elaborazione verrà interrotta appena possibile")
            self.dlg.btn_stop.setEnabled(False)
    
    def reset_processing_state(self):
        """Ripristina lo stato dell'interfaccia dopo l'elaborazione"""
        self.processing_active = False
        self.dlg.btn_stop.setEnabled(False)
        self.dlg.btn_process.setEnabled(True)
    
    def safe_cleanup_and_close(self, cleanup_func):
        """Esegue la pulizia in modo sicuro senza far crashare il plugin"""
        try:
            # Esegui la funzione di pulizia
            cleanup_func()
        except Exception as e:
            # Se la pulizia fallisce, logga l'errore ma non far crashare il plugin
            print(f"Errore durante la pulizia: {e}")
            try:
                # Prova a resettare almeno l'interfaccia
                self.dlg.le_folder.setFilePath("")
                self.dlg.le_temp_folder.setFilePath("")
                self.dlg.le_map_output.setText("")
                self.dlg.le_ple_output.setText("")
                self.dlg._reset_comuni_widget()
                self.dlg.cb_file_type.setCurrentIndex(0)
                self.dlg.cb_format.setCurrentIndex(0)
                self.dlg.cb_region.setCurrentIndex(0)
                self.dlg.text_log.append("Interfaccia resettata - pulizia file parziale")
            except Exception:
                pass
        
        # Non chiudere automaticamente il dialog per evitare crash
        # L'utente può chiuderlo manualmente se necessario

    def on_task_completed(self, success, result):
        """Gestisce il completamento del task"""
        global directory_temporanea
        
        if success:
            self.dlg.text_log.append("\nElaborazione completata con successo!")
            
            # Aggiorna le informazioni dei percorsi output
            if result.get('map_output') and result['map_count'] > 0:
                self.dlg.text_log.append(f"File MAP salvato in: {result['map_output']}")
            if result.get('ple_output') and result['ple_count'] > 0:
                self.dlg.text_log.append(f"File PLE salvato in: {result['ple_output']}")
            
            # Carica i layer se l'opzione è attiva
            if result.get('load_layers', False):
                self.dlg.text_log.append("\n<span style='color:#FF8C00;font-weight:bold;'>Caricamento layer in QGIS...</span>")

                granularity = result.get('output_granularity', 'unico')
                qml_path = os.path.join(self.plugin_dir, 'ple_style.qml')

                def load_map_layer(map_file, parent=None):
                    base_name = os.path.splitext(os.path.basename(map_file))[0]
                    layer = QgsVectorLayer(map_file, base_name, "ogr")
                    if layer.isValid():
                        QgsProject.instance().addMapLayer(layer, parent is None)
                        if parent is not None:
                            parent.addLayer(layer)
                        self.dlg.text_log.append(f"Layer MAP '{base_name}' caricato in QGIS")
                    else:
                        self.dlg.text_log.append(f"ERRORE: Impossibile caricare il layer MAP '{base_name}'")

                def load_ple_layer(ple_file, parent=None):
                    base_name = os.path.splitext(os.path.basename(ple_file))[0]
                    layer = QgsVectorLayer(ple_file, base_name, "ogr")
                    if layer.isValid():
                        if os.path.exists(qml_path):
                            layer.loadNamedStyle(qml_path)
                        QgsProject.instance().addMapLayer(layer, parent is None)
                        if parent is not None:
                            parent.addLayer(layer)
                        self.dlg.text_log.append(f"Layer PLE '{base_name}' caricato in QGIS")
                    else:
                        self.dlg.text_log.append(f"ERRORE: Impossibile caricare il layer PLE '{base_name}'")

                if granularity == 'unico':
                    if result.get('map_output') and result['map_count'] > 0:
                        load_map_layer(result['map_output'])
                    if result.get('ple_output') and result['ple_count'] > 0:
                        load_ple_layer(result['ple_output'])
                else:
                    # Crea un gruppo nel layer panel
                    label_gran = "per provincia" if granularity == 'per_provincia' else "per comune"
                    group_name = f"Catasto - {label_gran}"
                    root = QgsProject.instance().layerTreeRoot()
                    group = root.insertGroup(0, group_name)
                    for map_file in result.get('map_outputs', []):
                        load_map_layer(map_file, parent=group)
                    for ple_file in result.get('ple_outputs', []):
                        load_ple_layer(ple_file, parent=group)

            # Mostra i tempi di elaborazione
            if result.get('processing_times'):
                self.dlg.text_log.append("\nTempi di elaborazione:")
                for file_type, processing_time in result['processing_times'].items():
                    self.dlg.text_log.append(f"- {file_type}: {processing_time}")
            
            # Aggiorna la directory temporanea per la pulizia successiva
            if result.get('temp_dir'):
                directory_temporanea = result['temp_dir']
                self.dlg.text_log.append(f"\nDirectory temporanea: {directory_temporanea}")
                self.dlg.text_log.append("Usa il pulsante 'Pulisci' per eliminare i file temporanei")
        else:
            if result.get('cancelled'):
                self.dlg.text_log.append("\n<span style='color:orange;font-weight:bold;'>Elaborazione annullata dall'utente</span>")
            else:
                self.dlg.text_log.append("\n<span style='color:red;font-weight:bold;'>Elaborazione non completata</span>")
                if result.get('exception'):
                    self.dlg.text_log.append(f"Errore: {str(result.get('exception'))}")
        
        # Aggiorna titolo finestra
        self.dlg.setWindowTitle("Catasto IT GML Merger PRO - Elaborazione completata")
        
        # Ripristina lo stato dell'interfaccia
        self.reset_processing_state()

class GmlProcessingTask(QgsTask):
    """Task per l'elaborazione dei file GML in background"""
    
    # Definizione dei segnali per comunicare con l'interfaccia
    log_message = pyqtSignal(str)
    task_completed = pyqtSignal(bool, object)
    
    def __init__(self, description, inputs):
        super().__init__(description, QgsTask.CanCancel)
        self.inputs = inputs
        self.directory_temporanea = None
        self.exception = None
        self.processing_times = {}
        self.result = {}
    
    def run(self):
        """Metodo principale eseguito in background"""
        temp_dir = None
        try:
            # Creiamo una directory temporanea minima
            if self.inputs.get('temp_folder'):
                # Usa la cartella temporanea personalizzata
                temp_dir = tempfile.mkdtemp(dir=self.inputs['temp_folder'])
                self.log_message.emit(f"Directory temporanea personalizzata creata: {temp_dir}\n")
            else:
                # Usa la cartella temporanea di sistema
                temp_dir = tempfile.mkdtemp()
                self.log_message.emit(f"Directory temporanea di sistema creata: {temp_dir}\n")
            
            self.directory_temporanea = temp_dir
            
            # Crea le cartelle di output per i file GML solo al bisogno
            map_folder = os.path.join(temp_dir, "map_files")
            ple_folder = os.path.join(temp_dir, "ple_files")
            
            if self.inputs["file_type"] in ["Mappe (MAP)", "Entrambi"]:
                os.makedirs(map_folder, exist_ok=True)
            
            if self.inputs["file_type"] in ["Particelle (PLE)", "Entrambi"]:
                os.makedirs(ple_folder, exist_ok=True)
            
            # Download del file zip principale
            self.log_message.emit("Download del file zip principale...\n")
            self.setProgress(5)  # 5% dopo inizializzazione
            
            main_zip_path = os.path.join(temp_dir, "downloaded.zip")
            with urllib.request.urlopen(self.inputs["url"], timeout=120) as response:
                with open(main_zip_path, 'wb') as out_file:
                    shutil.copyfileobj(response, out_file)
            
            self.setProgress(15)  # 15% dopo download

            # Filtra per provincia
            province_codes = [p.strip().upper() for p in self.inputs['province_code'].split(',')]
            self.log_message.emit(f"Province selezionate: {', '.join(province_codes)}")
            
            # Modifica il nome dell'output con tutti i codici provincia
            province_suffix = "_".join(province_codes)
            if self.inputs["file_type"] in ["Mappe (MAP)", "Entrambi"]:
                base_name = os.path.splitext(self.inputs["map_output"])[0]
                ext = os.path.splitext(self.inputs["map_output"])[1]
                self.inputs["map_output"] = f"{base_name}_{province_suffix}{ext}"
                self.log_message.emit(f"Output MAP aggiornato: {self.inputs['map_output']}")
            
            if self.inputs["file_type"] in ["Particelle (PLE)", "Entrambi"]:
                base_name = os.path.splitext(self.inputs["ple_output"])[0]
                ext = os.path.splitext(self.inputs["ple_output"])[1]
                self.inputs["ple_output"] = f"{base_name}_{province_suffix}{ext}"
                self.log_message.emit(f"Output PLE aggiornato: {self.inputs['ple_output']}")

            # Aggiunge suffisso con codici Belfiore se il filtro comuni è attivo
            comuni_filter = self.inputs.get('comuni_filter', [])
            if comuni_filter:
                comuni_suffix = "_".join(comuni_filter)
                if self.inputs["file_type"] in ["Mappe (MAP)", "Entrambi"]:
                    base_name = os.path.splitext(self.inputs["map_output"])[0]
                    ext = os.path.splitext(self.inputs["map_output"])[1]
                    self.inputs["map_output"] = f"{base_name}_{comuni_suffix}{ext}"
                    self.log_message.emit(f"Output MAP con filtro comuni: {self.inputs['map_output']}")
                if self.inputs["file_type"] in ["Particelle (PLE)", "Entrambi"]:
                    base_name = os.path.splitext(self.inputs["ple_output"])[0]
                    ext = os.path.splitext(self.inputs["ple_output"])[1]
                    self.inputs["ple_output"] = f"{base_name}_{comuni_suffix}{ext}"
                    self.log_message.emit(f"Output PLE con filtro comuni: {self.inputs['ple_output']}")

            # Contatori per i file
            ple_count = map_count = 0
            
            # Usa un buffer di memoria per i nomi dei file estratti per evitare duplicazioni
            extracted_files = set()
            
            # Gestione dei file ZIP annidati
            self.log_message.emit("Elaborazione file...")
            
            self.setProgress(20)  # 20% prima dell'estrazione
            
            with ZipFile(main_zip_path, "r") as main_zip:
                # Estrai solo l'elenco dei file, non il contenuto
                province_zips = [f for f in main_zip.namelist() if f.endswith('.zip')]
                
                # Filtra per province selezionate
                filtered_province_zips = []
                for prov_zip in province_zips:
                    prov_name = os.path.basename(prov_zip)
                    for code in province_codes:
                        if code in prov_name.upper():
                            filtered_province_zips.append(prov_zip)
                            self.log_message.emit(f"Provincia trovata: {prov_name}")
                            break
                
                if not filtered_province_zips:
                    self.log_message.emit(f"ATTENZIONE: Nessuna provincia trovata con i codici '{self.inputs['province_code']}'")
                    self.log_message.emit("Controlla che i codici provincia siano corretti e riprova")
                    return False
                
                # Processa ogni provincia selezionata
                total_provinces = len(filtered_province_zips)
                
                for idx, prov_zip_path in enumerate(filtered_province_zips):
                    if self.isCanceled():
                        self.log_message.emit("Elaborazione annullata dall'utente")
                        return False
                        
                    prov_progress_base = 20  # Iniziamo dal 20%
                    prov_progress_range = 30  # Le province coprono il 30% dell'avanzamento totale
                    prov_progress = prov_progress_base + (idx / total_provinces) * prov_progress_range
                    self.setProgress(int(prov_progress))
                    
                    prov_name = os.path.basename(prov_zip_path)
                    prov_code = os.path.splitext(prov_name)[0].upper()
                    self.log_message.emit(f"Elaborazione provincia: {prov_name}")
                    
                    # Estrai il file ZIP della provincia in un BytesIO per processarlo in memoria
                    with main_zip.open(prov_zip_path) as prov_zip_file:
                        prov_zip_data = io.BytesIO(prov_zip_file.read())
                        
                        with ZipFile(prov_zip_data) as prov_zip:
                            comuni_zips = [f for f in prov_zip.namelist() if f.endswith('.zip')]

                            # Calcola il totale dei comuni per la barra di progresso
                            total_comuni = len(comuni_zips)
                            processed_comuni = 0

                            # Log diagnostico: mostra i primi nomi dei ZIP trovati nella provincia
                            if comuni_zips:
                                sample = [os.path.basename(f) for f in comuni_zips[:5]]
                                self.log_message.emit(f"ZIP comuni trovati (primi {len(sample)}): {', '.join(sample)}")
                            else:
                                self.log_message.emit("Nessun ZIP comune trovato nella provincia (struttura diversa?)")

                            for com_zip_path in comuni_zips:
                                if self.isCanceled():
                                    self.log_message.emit("Elaborazione interrotta dall'utente")
                                    return False

                                com_name = os.path.basename(com_zip_path)

                                # Codice Belfiore comune: "A070_AGIRA.zip" → "A070"
                                com_belfiore = os.path.splitext(com_name)[0].split('_')[0].upper()

                                # Filtro per codice Belfiore comune (opzionale)
                                comuni_filter = self.inputs.get('comuni_filter', [])
                                if comuni_filter and com_belfiore not in comuni_filter:
                                    continue

                                processed_comuni += 1

                                # Calcola progresso per i comuni all'interno della provincia
                                comuni_progress = prov_progress + (processed_comuni / total_comuni) * (prov_progress_range / total_provinces)
                                if processed_comuni % 10 == 0 or processed_comuni == total_comuni:
                                    self.setProgress(int(comuni_progress))
                                    self.log_message.emit(f"Elaborazione comune {processed_comuni}/{total_comuni}: {com_name}")
                                
                                # Estrai il file ZIP del comune in un BytesIO
                                with prov_zip.open(com_zip_path) as com_zip_file:
                                    com_zip_data = io.BytesIO(com_zip_file.read())
                                    
                                    with ZipFile(com_zip_data) as com_zip:
                                        gml_files = [f for f in com_zip.namelist() if f.endswith('.gml')]
                                        
                                        # Estrai solo i file GML richiesti
                                        for gml_file in gml_files:
                                            file_name = os.path.basename(gml_file)
                                            
                                            # Verifica se il file è già stato estratto (evita duplicati)
                                            if file_name in extracted_files:
                                                continue
                                                
                                            # Verifica il tipo di file e se è richiesto
                                            is_ple = "_ple" in file_name.lower()
                                            is_map = "_map" in file_name.lower()
                                            
                                            if (is_ple and self.inputs["file_type"] in ["Particelle (PLE)", "Entrambi"]) or \
                                               (is_map and self.inputs["file_type"] in ["Mappe (MAP)", "Entrambi"]):

                                                # Determina la cartella di destinazione in base alla granularità
                                                granularity = self.inputs.get('output_granularity', 'unico')
                                                base_folder = ple_folder if is_ple else map_folder
                                                if granularity == 'per_provincia':
                                                    dest_folder = os.path.join(base_folder, prov_code)
                                                elif granularity == 'per_comune':
                                                    dest_folder = os.path.join(base_folder, com_belfiore)
                                                else:
                                                    dest_folder = base_folder
                                                os.makedirs(dest_folder, exist_ok=True)
                                                dest_path = os.path.join(dest_folder, file_name)
                                                
                                                # Estrai il file nella cartella appropriata
                                                with com_zip.open(gml_file) as source, \
                                                     open(dest_path, 'wb') as target:
                                                    shutil.copyfileobj(source, target)
                                                
                                                # Aggiorna contatori
                                                if is_ple:
                                                    ple_count += 1
                                                else:
                                                    map_count += 1
                                                
                                                # Aggiungi al set per evitare duplicati
                                                extracted_files.add(file_name)

                        del prov_zip_data
                        gc.collect()

            self.log_message.emit(f"\nFile estratti: {ple_count} PLE, {map_count} MAP")
            self.setProgress(50)  # 50% dopo estrazione
            
            # Libera memoria
            extracted_files.clear()
            gc.collect()
            
            # Esegui l'unione dei file
            self.processing_times = {}
            granularity = self.inputs.get('output_granularity', 'unico')

            def get_merge_subdirs(base_folder):
                """Restituisce lista (key, folder) da mergiare in base alla granularità."""
                if granularity == 'unico':
                    return [(None, base_folder)]
                subdirs = sorted([
                    d for d in os.listdir(base_folder)
                    if os.path.isdir(os.path.join(base_folder, d))
                ])
                return [(key, os.path.join(base_folder, key)) for key in subdirs]

            def build_output_path(base_output, key):
                """Aggiunge suffisso _{key} al percorso output se key è specificato."""
                if key is None:
                    return base_output
                base, ext = os.path.splitext(base_output)
                return f"{base}_{key}{ext}"

            map_outputs = []
            ple_outputs = []

            if self.inputs["file_type"] in ["Mappe (MAP)", "Entrambi"] and map_count > 0 and not self.isCanceled():
                for key, src_folder in get_merge_subdirs(map_folder):
                    if self.isCanceled():
                        break
                    out_path = build_output_path(self.inputs["map_output"], key)
                    label = "MAP" + (f" ({key})" if key else "")
                    self.log_message.emit(f"\nUnione files {label}\n")
                    t = self.merge_files(src_folder, out_path, "MAP")
                    if t:
                        self.processing_times[label] = t
                        map_outputs.append(out_path)
                self.setProgress(75)

            if self.inputs["file_type"] in ["Particelle (PLE)", "Entrambi"] and ple_count > 0 and not self.isCanceled():
                self.log_message.emit("<span style='color:blue;font-weight:bold;'>Attendere prego, operazione costosa!<br>Puoi ridurre ad icona e continuare a lavorare con QGIS!</span>")
                for key, src_folder in get_merge_subdirs(ple_folder):
                    if self.isCanceled():
                        break
                    out_path = build_output_path(self.inputs["ple_output"], key)
                    label = "PLE" + (f" ({key})" if key else "")
                    self.log_message.emit(f"\nUnione files {label}\n")
                    t = self.merge_files(src_folder, out_path, "PLE")
                    if t:
                        self.processing_times[label] = t
                        ple_outputs.append(out_path)
                if self.inputs["file_type"] == "Entrambi":
                    self.setProgress(90)
                else:
                    self.setProgress(75)

            # Esegui la riproiezione se necessario
            target_crs = self.inputs.get('target_crs', 'EPSG:6706')

            if target_crs != 'EPSG:6706' and not self.isCanceled():
                self.log_message.emit(f"\n<span style='color:blue;font-weight:bold;'>Riproiezione dei file al sistema {target_crs}...</span>")

                new_map_outputs = []
                for out_path in map_outputs:
                    if os.path.exists(out_path):
                        start = datetime.now()
                        rep = self.reproject_layer(out_path, target_crs, "MAP")
                        self.processing_times[f"Riproiezione MAP {os.path.basename(out_path)}"] = datetime.now() - start
                        new_map_outputs.append(rep if rep else out_path)
                    else:
                        new_map_outputs.append(out_path)
                map_outputs = new_map_outputs

                new_ple_outputs = []
                for out_path in ple_outputs:
                    if os.path.exists(out_path):
                        start = datetime.now()
                        rep = self.reproject_layer(out_path, target_crs, "PLE")
                        self.processing_times[f"Riproiezione PLE {os.path.basename(out_path)}"] = datetime.now() - start
                        new_ple_outputs.append(rep if rep else out_path)
                    else:
                        new_ple_outputs.append(out_path)
                ple_outputs = new_ple_outputs

            self.log_message.emit("\nElaborazione completata!")
            self.setProgress(100)

            # Prepara risultati
            self.result = {
                'map_count': map_count,
                'ple_count': ple_count,
                'map_outputs': map_outputs,
                'ple_outputs': ple_outputs,
                'map_output': map_outputs[0] if map_outputs else None,
                'ple_output': ple_outputs[0] if ple_outputs else None,
                'output_granularity': granularity,
                'temp_dir': temp_dir,
                'processing_times': self.processing_times,
                'load_layers': self.inputs.get("load_layers", False),
                'target_crs': self.inputs.get("target_crs", "EPSG:6706"),
            }
            
            return True
            
        except Exception as e:
            self.log_message.emit(f"\nSi è verificato un errore durante l'elaborazione: {str(e)}")
            import traceback
            self.log_message.emit(f"\nDettagli errore:\n{traceback.format_exc()}")
            self.exception = e
            return False
    
    def merge_files(self, source_folder, output_file, file_type):
        """Metodo per unire i file GML e applicare trasformazioni"""
        start_time = datetime.now()

        source_files = [
            os.path.join(source_folder, f)
            for f in os.listdir(source_folder)
            if f.endswith(".gml")
        ]

        if source_files:
            # Usa la directory temporanea principale invece di crearne una nuova
            temp_dir = self.directory_temporanea
            # Crea una sottodirectory specifica per l'operazione di merge 
            merge_subdir = os.path.join(temp_dir, f"merge_{file_type}")
            try:
                os.makedirs(merge_subdir, exist_ok=True)
            except Exception as e:
                self.log_message.emit(f"ERRORE: Impossibile creare directory di merge: {str(e)}")
                return None
                
            temp_merge = os.path.join(merge_subdir, f"temp_merge_{file_type}_{int(time.time())}.gpkg")
            
            # Verifica spazio disco disponibile nella directory temporanea
            try:
                import shutil
                free_space = shutil.disk_usage(merge_subdir).free
                free_space_gb = free_space / (1024**3)
                self.log_message.emit(f"Spazio libero in directory temporanea: {free_space_gb:.1f} GB")
                
                if free_space_gb < 1.0:  # Meno di 1GB libero
                    self.log_message.emit(f"ATTENZIONE: Poco spazio libero ({free_space_gb:.1f} GB) nella directory temporanea")
            except Exception as e:
                self.log_message.emit(f"Avviso: Impossibile verificare spazio disco: {str(e)}")

            # Verifica directory di output e creala se necessario
            output_dir = os.path.dirname(output_file)
            if output_dir and not os.path.exists(output_dir):
                try:
                    os.makedirs(output_dir, exist_ok=True)
                    self.log_message.emit(f"Directory di output creata: {output_dir}")
                except Exception as e:
                    self.log_message.emit(f"ERRORE: Impossibile creare la directory di output: {str(e)}")
                    return None

            # Verifica che la cartella di output sia scrivibile
            try:
                test_file = os.path.join(output_dir, "test_write.tmp")
                with open(test_file, 'w') as f:
                    f.write("test")
                os.remove(test_file)
            except Exception as e:
                self.log_message.emit(f"ERRORE: La directory di output non è scrivibile: {str(e)}")
                return None

            try:
                # Evita blocchi sui file in uso
                project = QgsProject.instance()
                for layer_id, layer in list(project.mapLayers().items()):
                    if output_file in layer.source() or temp_merge in layer.source():
                        project.removeMapLayer(layer_id)
                
                # Rimuovi il file di output se esiste già
                if os.path.exists(output_file):
                    try:
                        os.remove(output_file)
                        self.log_message.emit(f"File di output esistente rimosso: {output_file}")
                    except Exception as e:
                        self.log_message.emit(f"ATTENZIONE: Impossibile rimuovere il file di output esistente: {str(e)}")
                        # Modifica il nome del file per evitare conflitti
                        base_name = os.path.splitext(output_file)[0]
                        ext = os.path.splitext(output_file)[1]
                        output_file = f"{base_name}_{int(time.time())}{ext}"
                        self.log_message.emit(f"Usando nome file alternativo: {output_file}")

                # Forza il garbage collection prima di operazioni critiche
                gc.collect()
                time.sleep(0.5)

                self.log_message.emit(f"Unione file {file_type}...")
                self.log_message.emit(f"File temporaneo merge: {temp_merge}")
                self.log_message.emit(f"Numero file da unire: {len(source_files)}")

                # Verifica che il percorso del file temporaneo sia valido
                if not os.access(os.path.dirname(temp_merge), os.W_OK):
                    self.log_message.emit(f"ERRORE: Directory temporanea non scrivibile: {os.path.dirname(temp_merge)}")
                    return None

                # Verifica che i file sorgente esistano, siano leggibili e validi
                valid_source_files = []
                skipped_files = []
                for sf in source_files:
                    if os.path.exists(sf) and os.access(sf, os.R_OK):
                        try:
                            test_layer = QgsVectorLayer(sf, "test_validity", "ogr")
                            if test_layer.isValid():
                                valid_source_files.append(sf)
                            else:
                                skipped_files.append(os.path.basename(sf))
                                self.log_message.emit(f"AVVISO: File GML non valido, saltato: {os.path.basename(sf)}")
                        except Exception as e:
                            skipped_files.append(os.path.basename(sf))
                            self.log_message.emit(f"AVVISO: Errore validazione file, saltato: {os.path.basename(sf)} ({str(e)})")
                    else:
                        self.log_message.emit(f"ATTENZIONE: File sorgente non accessibile: {sf}")

                if skipped_files:
                    self.log_message.emit(f"File GML non validi saltati ({len(skipped_files)}): {', '.join(skipped_files)}")

                if not valid_source_files:
                    self.log_message.emit("ERRORE: Nessun file sorgente valido trovato")
                    return None

                if len(valid_source_files) != len(source_files):
                    self.log_message.emit(f"Procedo con {len(valid_source_files)} file validi su {len(source_files)} totali")

                merge_params = {
                    "LAYERS": valid_source_files,
                    "CRS": QgsCoordinateReferenceSystem('EPSG:6706'),
                    "OUTPUT": temp_merge,
                }
                
                try:
                    processing.run("native:mergevectorlayers", merge_params)
                    self.log_message.emit(f"Unione completata: {temp_merge}")
                except Exception as e:
                    self.log_message.emit(f"ERRORE durante l'unione standard: {str(e)}")
                    self.log_message.emit("Tentativo con strategia alternativa...")
                    
                    # Strategia alternativa: prova con batch più piccoli
                    try:
                        temp_merge = self.merge_files_alternative(valid_source_files, temp_merge, file_type)
                        if temp_merge is None:
                            self.log_message.emit("ERRORE: Anche la strategia alternativa è fallita")
                            return None
                        self.log_message.emit("Unione alternativa completata con successo")
                    except Exception as e2:
                        self.log_message.emit(f"ERRORE anche con strategia alternativa: {str(e2)}")
                        # Prova a usare una directory diversa se possibile
                        if hasattr(self, 'inputs') and self.inputs.get('temp_folder'):
                            self.log_message.emit("Prova a specificare una directory temporanea diversa con più spazio disponibile")
                        else:
                            self.log_message.emit("Prova a specificare una directory temporanea personalizzata nell'interfaccia")
                        return None

                # Chiudi esplicitamente i riferimenti ai layer che potrebbero utilizzare il file temporaneo
                for layer_id, layer in list(project.mapLayers().items()):
                    if temp_merge in layer.source():
                        project.removeMapLayer(layer_id)
                
                # Forza il garbage collection
                gc.collect()
                time.sleep(0.5)

                # Assicurati sempre che la directory esista
                if output_dir and not os.path.exists(output_dir):
                    os.makedirs(output_dir, exist_ok=True)

                # Processo semplificato: filtro direttamente nel formato desiderato
                filter_params = {
                    "INPUT": temp_merge,
                    "FIELDS": ["fid", "gml_id", "ADMINISTRATIVEUNIT"],
                    "OUTPUT": output_file
                }

                self.log_message.emit(f"Filtro attributi per {file_type}...")
                result = processing.run("native:retainfields", filter_params)
                output_file = result['OUTPUT']

                # Fix CRS: native:retainfields non propaga il metadato SRS nel GPKG.
                # Scriviamo EPSG:6706 direttamente nelle tabelle SRS del file GPKG.
                if output_file.lower().endswith('.gpkg'):
                    try:
                        crs_ref = QgsCoordinateReferenceSystem('EPSG:6706')
                        conn = sqlite3.connect(output_file)
                        c = conn.cursor()
                        c.execute(
                            "INSERT OR REPLACE INTO gpkg_spatial_ref_sys "
                            "(srs_name, srs_id, organization, organization_coordsys_id, definition) "
                            "VALUES (?,?,?,?,?)",
                            (crs_ref.description(), 6706, 'EPSG', 6706, crs_ref.toWkt())
                        )
                        c.execute("UPDATE gpkg_geometry_columns SET srs_id=6706")
                        c.execute("UPDATE gpkg_contents SET srs_id=6706")
                        conn.commit()
                        conn.close()
                        self.log_message.emit("CRS EPSG:6706 assegnato al file GPKG")
                    except Exception as e:
                        self.log_message.emit(f"Avviso: impossibile assegnare CRS al GPKG: {e}")

                # Ottimizzazione della generazione dei campi utilizzando operazioni in batch
                self.log_message.emit(f"Aggiunta campo 'foglio' al layer {file_type}...")
                output_layer = QgsVectorLayer(output_file, f"{file_type}_Uniti", "ogr")
                
                if output_layer.isValid():
                    # Prepara tutti i campi da aggiungere in una singola operazione
                    fields_to_add = [QgsField("foglio", QVariant.String)]
                    if file_type == "PLE":
                        self.log_message.emit("Aggiunta campo 'particella'...")
                        fields_to_add.append(QgsField("particella", QVariant.String))
                        # Aggiungi campo sezione censuaria se richiesto
                        if self.inputs.get("add_sezione_censuaria", False):
                            self.log_message.emit("Aggiunta campo 'sez_censuaria'...")
                            fields_to_add.append(QgsField("sez_censuaria", QVariant.String, len=1))
                    # Aggiungi campo nome comune se richiesto (vale per MAP e PLE)
                    if self.inputs.get("add_nome_comune", False):
                        self.log_message.emit("Aggiunta campo 'comune'...")
                        fields_to_add.append(QgsField("comune", QVariant.String))
                    
                    # Inizia la transazione per le modifiche in batch
                    output_layer.startEditing()
                    output_layer.dataProvider().addAttributes(fields_to_add)
                    output_layer.updateFields()
                    
                    # Ottieni gli indici una sola volta fuori dal ciclo
                    foglio_idx = output_layer.fields().indexFromName("foglio")
                    particella_idx = output_layer.fields().indexFromName("particella") if file_type == "PLE" else -1
                    sez_censuaria_idx = output_layer.fields().indexFromName("sez_censuaria") if file_type == "PLE" and self.inputs.get("add_sezione_censuaria", False) else -1
                    gml_id_idx = output_layer.fields().indexFromName("gml_id")
                    au_idx = output_layer.fields().indexFromName("ADMINISTRATIVEUNIT")
                    comune_idx = output_layer.fields().indexFromName("comune") if self.inputs.get("add_nome_comune", False) else -1

                    # Calcola valori una sola volta
                    needs_particella = file_type == "PLE" and particella_idx >= 0
                    needs_sez_censuaria = file_type == "PLE" and sez_censuaria_idx >= 0
                    needs_nome_comune = comune_idx >= 0 and au_idx >= 0
                    
                    # Inizializza il buffer per le modifiche prima di usarlo
                    changes_buffer = {}
                    
                    # Usa una singola passata per elaborare tutti i dati
                    for feature in output_layer.getFeatures():
                        feature_id = feature.id()
                        gml_id = feature[gml_id_idx]
                        
                        # Estrai foglio (posizioni 32-36) con controllo più efficiente
                        if len(gml_id) > 36:
                            foglio = gml_id[32:36]
                            changes_buffer[feature_id] = {foglio_idx: foglio}
                            
                            # Estrai particella per PLE (dalla posizione 39 in poi)
                            if needs_particella and len(gml_id) > 39:
                                particella = gml_id[39:]
                                changes_buffer[feature_id][particella_idx] = particella
                            
                            # Estrai sezione censuaria per PLE (indice Python 31, 1 carattere prima del foglio)
                            if needs_sez_censuaria and len(gml_id) > 32:
                                sez_censuaria = gml_id[31:32]
                                changes_buffer[feature_id][sez_censuaria_idx] = sez_censuaria

                        # Aggiungi nome comune da ADMINISTRATIVEUNIT (codice Belfiore)
                        if needs_nome_comune:
                            belfiore = feature[au_idx]
                            if belfiore:
                                nome_comune = COMUNI_BY_CODE.get(str(belfiore).upper(), ('',))[0]
                                changes_buffer.setdefault(feature_id, {})[comune_idx] = nome_comune
                    
                    # Applica tutte le modifiche in batch
                    batch_size = 500  # Controlla annullamento ogni 500 feature
                    batch_count = 0
                    for feature_id, attrs in changes_buffer.items():
                        for field_idx, value in attrs.items():
                            output_layer.changeAttributeValue(feature_id, field_idx, value)
                        
                        batch_count += 1
                        if batch_count % batch_size == 0 and self.isCanceled():
                            output_layer.rollBack()
                            self.log_message.emit("Operazione annullata dall'utente")
                            return None
                    
                    # Finalizza le modifiche e controlla errori
                    success = output_layer.commitChanges()
                    if success:
                        self.log_message.emit(f"Campi calcolati correttamente per il layer {file_type}")
                    else:
                        self.log_message.emit(f"ERRORE: Impossibile aggiornare i campi per il layer {file_type}")
                        self.log_message.emit(str(output_layer.commitErrors()))
                else:
                    self.log_message.emit(f"ERRORE: Il layer di output {file_type} non è valido")

                # Pulizia risorse temporanee in modo più robusto
                try:
                    # Prima rilascia i riferimenti QGIS al file
                    for layer_id, layer in list(QgsProject.instance().mapLayers().items()):
                        if temp_merge in layer.source():
                            QgsProject.instance().removeMapLayer(layer_id)
                    
                    # Libera memoria e dai tempo al sistema
                    output_layer = None
                    gc.collect()
                    time.sleep(1)
                    
                    # Ora prova a cancellare i file temporanei
                    if os.path.exists(temp_merge):
                        try:
                            os.remove(temp_merge)
                            self.log_message.emit(f"File temporaneo rimosso: {os.path.basename(temp_merge)}")
                        except Exception as e:
                            self.log_message.emit(f"Impossibile rimuovere il file temporaneo: {str(e)}")
                    
                    # Rimuovi anche la directory temporanea se vuota
                    if os.path.exists(temp_dir) and len(os.listdir(temp_dir)) == 0:
                        os.rmdir(temp_dir)
                        self.log_message.emit("Directory temporanea rimossa")
                except Exception as e:
                    self.log_message.emit(f"Nota: Impossibile rimuovere alcuni file temporanei: {str(e)}")
                
                end_time = datetime.now()
                return end_time - start_time

            except Exception as e:
                self.log_message.emit(f"ERRORE: Si è verificato un problema durante l'unione dei file: {str(e)}")
                # Aggiungi traceback per debugging
                import traceback
                self.log_message.emit(f"Dettagli: {traceback.format_exc()}")
                return None

        return None
        
    def finished(self, result):
        """Viene chiamato quando il task è completato"""
        if self.isCanceled():
            self.task_completed.emit(False, {'cancelled': True})
        else:
            self.task_completed.emit(result, self.result)

    def reproject_layer(self, input_file, target_crs, file_type):
        """Riproietta un layer vettoriale nel CRS specificato"""
        try:
            self.log_message.emit(f"Riproiezione del layer {file_type} nel sistema {target_crs}...")
            
            # Crea il nome del file di output con il suffisso del CRS
            basename = os.path.splitext(input_file)[0]
            extension = os.path.splitext(input_file)[1]
            crs_suffix = target_crs.replace(":", "_")  # Trasforma "EPSG:4326" in "EPSG_4326"
            output_file = f"{basename}_{crs_suffix}{extension}"
            
            # Se il file esiste già, rimuovilo
            if os.path.exists(output_file):
                try:
                    os.remove(output_file)
                    self.log_message.emit(f"File riproiettato esistente rimosso: {os.path.basename(output_file)}")
                except Exception as e:
                    self.log_message.emit(f"ATTENZIONE: Impossibile rimuovere il file riproiettato esistente: {str(e)}")
                    # Usa un timestamp per evitare conflitti
                    output_file = f"{basename}_{crs_suffix}_{int(time.time())}{extension}"
            
            # Parametri per la riproiezione
            params = {
                'INPUT': input_file,
                'TARGET_CRS': target_crs,
                'OUTPUT': output_file
            }
            
            # Esegui la riproiezione
            result = processing.run("native:reprojectlayer", params)
            output_file = result['OUTPUT']
            
            self.log_message.emit(f"Riproiezione completata: {os.path.basename(output_file)}")
            return output_file
        
        except Exception as e:
            self.log_message.emit(f"ERRORE durante la riproiezione del layer {file_type}: {str(e)}")
            import traceback
            self.log_message.emit(f"Dettagli: {traceback.format_exc()}")
            return None

    def merge_files_alternative(self, source_files, output_path, file_type):
        """Strategia alternativa di merge che elabora i file in batch più piccoli"""
        try:
            self.log_message.emit(f"Tentativo merge alternativo con {len(source_files)} file...")
            
            # Rimuovi il file di output se esiste già
            if os.path.exists(output_path):
                try:
                    os.remove(output_path)
                except Exception as e:
                    self.log_message.emit(f"Attenzione: impossibile rimuovere file esistente: {e}")
            
            # Prima strategia: prova con batch più piccoli (10 file alla volta)
            batch_size = 10
            temp_files = []
            
            for i in range(0, len(source_files), batch_size):
                if self.isCanceled():
                    return None
                    
                batch = source_files[i:i + batch_size]
                batch_output = f"{os.path.splitext(output_path)[0]}_batch_{i//batch_size}.gpkg"
                
                self.log_message.emit(f"Elaborazione batch {i//batch_size + 1}: {len(batch)} file")
                
                # Prova a unire questo batch con parametri migliorati per evitare conflitti FID
                batch_params = {
                    "LAYERS": batch,
                    "CRS": QgsCoordinateReferenceSystem('EPSG:6706'),
                    "OUTPUT": batch_output,
                    "SEPARATE_LAYERS": False,
                }
                
                try:
                    # Prova prima con QGIS processing
                    processing.run("native:mergevectorlayers", batch_params)
                    temp_files.append(batch_output)
                    self.log_message.emit(f"Batch {i//batch_size + 1} completato")
                except Exception as e:
                    self.log_message.emit(f"Errore nel batch {i//batch_size + 1} con QGIS: {str(e)}")
                    # Prova con merge GDAL alternativo
                    try:
                        success = self.merge_with_gdal(batch, batch_output, file_type)
                        if success:
                            temp_files.append(batch_output)
                            self.log_message.emit(f"Batch {i//batch_size + 1} completato con GDAL")
                        else:
                            # Se anche GDAL fallisce, usa singoli file
                            for single_file in batch:
                                if os.path.exists(single_file) and os.path.getsize(single_file) > 0:
                                    temp_files.append(single_file)
                    except Exception as e2:
                        self.log_message.emit(f"Errore anche con GDAL: {str(e2)}")
                        # Come ultimo resort, usa singoli file
                        for single_file in batch:
                            if os.path.exists(single_file) and os.path.getsize(single_file) > 0:
                                temp_files.append(single_file)
            
            if not temp_files:
                self.log_message.emit("Nessun file valido per il merge alternativo")
                return None
            
            # Ora unisci i file temporanei
            if len(temp_files) == 1:
                # Se c'è solo un file, copialo direttamente
                import shutil
                shutil.copy2(temp_files[0], output_path)
                self.log_message.emit("File unico copiato come output")
            else:
                # Unisci i file temporanei
                final_merge_params = {
                    "LAYERS": temp_files,
                    "CRS": QgsCoordinateReferenceSystem('EPSG:6706'),
                    "OUTPUT": output_path,
                }
                
                processing.run("native:mergevectorlayers", final_merge_params)
                self.log_message.emit("Merge finale completato")
            
            # Pulisci i file temporanei batch
            for temp_file in temp_files:
                if temp_file != output_path and os.path.exists(temp_file):
                    try:
                        os.remove(temp_file)
                    except Exception as e:
                        self.log_message.emit(f"Avviso: impossibile rimuovere file temporaneo {temp_file}: {e}")
            
            if os.path.exists(output_path) and os.path.getsize(output_path) > 0:
                return output_path
            else:
                self.log_message.emit("Il file di output non è stato creato correttamente")
                return None
                
        except Exception as e:
            self.log_message.emit(f"ERRORE nella strategia alternativa: {str(e)}")
            import traceback
            self.log_message.emit(f"Dettagli: {traceback.format_exc()}")
            return None

    def merge_with_gdal(self, source_files, output_path, file_type):
        """Merge files using GDAL/OGR directly to avoid FID conflicts"""
        first_source = None
        output_ds = None
        try:
            from osgeo import ogr, osr, gdal

            # Rimuovi il file di output se esiste
            if os.path.exists(output_path):
                os.remove(output_path)

            # Apri il primo file per ottenere la struttura
            first_source = ogr.Open(source_files[0])
            if not first_source:
                self.log_message.emit(f"Impossibile aprire il primo file: {source_files[0]}")
                return False

            first_layer = first_source.GetLayer(0)
            if not first_layer:
                self.log_message.emit("Impossibile ottenere il layer dal primo file")
                return False

            # Crea il file di output
            driver = ogr.GetDriverByName("GPKG")
            output_ds = driver.CreateDataSource(output_path)
            if not output_ds:
                self.log_message.emit(f"Impossibile creare il file di output: {output_path}")
                return False

            # Crea il layer di output con geometria generica per evitare conflitti POLYGON/MULTIPOLYGON
            geom_type = ogr.wkbUnknown  # Permette qualsiasi tipo di geometria
            srs = first_layer.GetSpatialRef()
            if srs is None:
                # Fallback: se il GML non espone la CRS, usa EPSG:6706 (RDN2008 nativo dei dati AE)
                srs = osr.SpatialReference()
                srs.ImportFromEPSG(6706)
            output_layer = output_ds.CreateLayer("merged_layer", srs, geom_type)

            # Copia la definizione dei campi dal primo layer
            layer_defn = first_layer.GetLayerDefn()
            for i in range(layer_defn.GetFieldCount()):
                field_defn = layer_defn.GetFieldDefn(i)
                # Aumenta la lunghezza massima per i campi stringa per evitare troncamenti
                if field_defn.GetType() == ogr.OFTString:
                    field_defn.SetWidth(254)  # Lunghezza massima per string field
                output_layer.CreateField(field_defn)

            first_source = None  # Chiudi il primo file

            # Processa tutti i file
            feature_count = 0
            for i, source_file in enumerate(source_files):
                if self.isCanceled():
                    return False

                self.log_message.emit(f"Processando file {i+1}/{len(source_files)}: {os.path.basename(source_file)}")

                source_ds = None
                try:
                    source_ds = ogr.Open(source_file)
                    if not source_ds:
                        self.log_message.emit(f"Impossibile aprire file: {source_file}")
                        continue

                    source_layer = source_ds.GetLayer(0)
                    if not source_layer:
                        self.log_message.emit(f"Impossibile ottenere layer da: {source_file}")
                        continue

                    # Copia tutte le feature dal layer sorgente
                    for feature in source_layer:
                        if self.isCanceled():
                            return False

                        # Crea una nuova feature per il layer di output
                        new_feature = ogr.Feature(output_layer.GetLayerDefn())

                        # Copia tutti i campi
                        for field_idx in range(feature.GetFieldCount()):
                            field_name = feature.GetFieldDefnRef(field_idx).GetName()
                            if output_layer.GetLayerDefn().GetFieldIndex(field_name) != -1:
                                new_feature.SetField(field_name, feature.GetField(field_idx))

                        # Copia la geometria
                        geom = feature.GetGeometryRef()
                        if geom:
                            new_feature.SetGeometry(geom.Clone())

                        # Aggiungi la feature al layer di output (il FID verrà assegnato automaticamente)
                        if output_layer.CreateFeature(new_feature) != ogr.OGRERR_NONE:
                            self.log_message.emit(f"Errore nell'aggiunta di una feature dal file: {source_file}")
                        else:
                            feature_count += 1

                        new_feature = None  # Cleanup
                finally:
                    source_ds = None  # Garantisce la chiusura del file sorgente anche in caso di errore

            self.log_message.emit(f"GDAL merge completato: {feature_count} features unite")
            return True

        except Exception as e:
            self.log_message.emit(f"ERRORE nel merge GDAL: {str(e)}")
            return False
        finally:
            first_source = None  # Garantisce la chiusura del primo file
            output_ds = None  # Garantisce la chiusura del file di output